sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '4'
before_install:
  - rm -rf node_modules
before_script:
  - npm prune
script:
  - ./bin/authorize-push.js
  - gh-pages-deploy
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
